
export const SIGN_IN = "Sign in"
export const RESET_PASSWORD = "Reset Password"
export const REGISTER_ACCOUNT = "Register Account"
export const CHOOSE_A_NEW_PASSWORD = "Choose a new password"
export const UPDATE_PASSWORD = "Update Password"
export const LOGIN= "Already have an account? Login"
export const CREATE_NEW_ACCOUNT = "Create new account"
export const ADD_EFFORTS = "Add Efforts"
export const EDIT_EFFORTS = "Edit Efforts"